language: node_js
node_js:
  - "9"

env:
  global:
    - NODE_ENV=test

cache:
  directories:
    - node_modules

before_script:
- env NODE_ENV=$TRAVIS_BRANCH npm run build
- npm start &
- $(npm bin)/wait-on http://localhost:3000

script:
- npm run test

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: './dist/'
    target_branch: master
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: prod
  - provider: surge
    skip_cleanup: true
    project: './dist/'
    domain: aya-experience.surge.sh
    on:
      branch: preprod

