language: node_js
node_js:
  - "9"

cache:
  directories:
    - node_modules

script:
- npm run test
- npm run generate


deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: './dist/'
    target_branch: ghpages
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master2
  - provider: surge
    skip_cleanup: true
    project: './dist/'
    domain: aya-experience.surge.sh
    on:
      branch: dev
