language: node_js

node_js:
- stable

env:
  global:
    secure: FdN7q8UxOe3m1xG4KvRHf5PYCGfHEG924XHq2oDSxvAenQc+NegGDsvKdP0u2BWlPUbZsLU9YIMzTdJWyKXGQt6kZPiQ4MUJK+g44CcS32ZEMw3lul3ufAJDn8Qc+p5VWWA9a0anVDNCnOHZ5VUIaluqojhqt/MKvuRHHEQnJl02myn7jC2yGc5AXDSkf5t1znEQpNRbuOwo1glJWq89qf0QxB1o1dFy0LJO3KDUwa6IiBdayxCDtmIacBF9cC2CfavD3AAyjyolDLaBlefXjz9gfBrk0mzgNx5C6bJzjqAM/8J2tH1Pe78cTn1nwLLZ5B9vTkxDK6iivvQZ6zONK+tPhRH7Cc87Z2aFbvWslM6smOue3vcZXopgT3MOwIlydkUIXaqcelF0pX85T/nks5YqYjHJMDXiIlmOtL3yrr8bD8RaUBpcJ+sLQMJSzlSqEdtULMMyATYUhWlrx2KWimkh1XLXsMDjcGW8gP+02GMpQhslXR3afXu6bFvCBmDhpIxU/m3tIJVFvi78DZR2ZZ66Co1oZopwhYx69CvcZGWldf6szCRvgzF7CKSdoz4tPQT9YpzN44p+oZzb8r0HK5M912KYOfg13VJbl2bkpcBnPNK1ZzPr8Z5NxynNajBheNSFpC4ZJnRSsc093VxZ2Cm0etj09q7qvI7fsuReyuo=

cache:
  directories:
  - node_modules

script:
- npm run build

after_success:
- if [ "$TRAVIS_BRANCH" = "dev" -a "$TRAVIS_PULL_REQUEST" = "false" ] && [[ ${TRAVIS_JOB_NUMBER} == *".1" ]]; then bin/ghpages; fi
