language: node_js
node_js:
  - "9"

env:
  global:
    - NODE_ENV=test

cache:
  directories:
    - node_modules

script:
- npm run extract # TODO: remove that after usin VueX
- npm run test
- env NODE_ENV=$TRAVIS_BRANCH npm run build


deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: './dist/'
    target_branch: master
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: prod
  - provider: surge
    skip_cleanup: true
    project: './dist/'
    domain: aya-experience.surge.sh
    on:
      branch: preprod
